/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesUsuario;

import executor.LoginUsuario;
import javax.swing.JOptionPane;
import usoGeral.Constantes;

/**
 * @author Smart Parking
 * @version 1.0
 */
public class Administracao extends javax.swing.JFrame {

    /**
     * Creates new form Adiministracao
     */
    public Administracao() {
        try{
            String vagasOcupadas, vagasRestantes, vagasPreferenciais;
            
            initComponents();
            
            vagasOcupadas = String.valueOf(Constantes.numeroVagasOcupadas + Constantes.numeroVagasOcupadasDeficientes);
            vagasRestantes = String.valueOf(Constantes.totalVagas - Integer.parseInt(vagasOcupadas.toString()));
            vagasPreferenciais = String.valueOf(Constantes.numeroVagasOcupadasDeficientes);
            VagasOcupadas.setText(vagasOcupadas);
            VagasRestantes.setText(vagasRestantes);
            Preferencial.setText(vagasPreferenciais);
            this.setLocationRelativeTo(null);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Erro no construtor Administracao. " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        VagasOcupadas = new javax.swing.JTextField();
        VagasRestantes = new javax.swing.JTextField();
        Voltar = new javax.swing.JButton();
        Historico = new javax.swing.JButton();
        CadastrarUsuario = new javax.swing.JButton();
        Preferencial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Administração");
        setResizable(false);

        jLabel1.setText("Estacionados");

        jLabel2.setText("Restantes");

        VagasOcupadas.setEditable(false);

        VagasRestantes.setEditable(false);

        Voltar.setText("Voltar");
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
        });
        Voltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VoltarKeyPressed(evt);
            }
        });

        Historico.setText("Histórico");
        Historico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoricoMouseClicked(evt);
            }
        });
        Historico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HistoricoKeyPressed(evt);
            }
        });

        CadastrarUsuario.setText("Cadastrar Usuário");
        CadastrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarUsuarioMouseClicked(evt);
            }
        });
        CadastrarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CadastrarUsuarioKeyPressed(evt);
            }
        });

        Preferencial.setEditable(false);

        jLabel3.setText("Preferenciais");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(VagasOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VagasRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(Preferencial, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CadastrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Historico)
                        .addGap(5, 5, 5)
                        .addComponent(Voltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VagasOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VagasRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Preferencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Voltar)
                    .addComponent(Historico)
                    .addComponent(CadastrarUsuario))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        this.retornarLogin();
    }//GEN-LAST:event_VoltarMouseClicked

    private void VoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VoltarKeyPressed
        if (evt.getKeyCode() == 10){
            this.retornarLogin();
        }
    }//GEN-LAST:event_VoltarKeyPressed

    private void HistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoricoMouseClicked
        this.chamarHistorico();
    }//GEN-LAST:event_HistoricoMouseClicked

    private void HistoricoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HistoricoKeyPressed
        if (evt.getKeyCode() == 10){
            this.chamarHistorico();
        }
    }//GEN-LAST:event_HistoricoKeyPressed

    private void CadastrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarUsuarioMouseClicked
        this.chamarCadastroUsuario();
    }//GEN-LAST:event_CadastrarUsuarioMouseClicked

    private void CadastrarUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CadastrarUsuarioKeyPressed
        if (evt.getKeyCode() == 10){
            this.chamarCadastroUsuario();
        }
    }//GEN-LAST:event_CadastrarUsuarioKeyPressed
    
    private void chamarHistorico (){
        TipoHistorico tipoHistorico = new TipoHistorico();
        tipoHistorico.show();
        this.dispose();  
    }
    
    private void retornarLogin (){
        LoginUsuario login = new LoginUsuario();
        login.show();
        this.dispose();
    }
    
    private void chamarCadastroUsuario (){
        CadastroUsuario cadastroUsuario = new CadastroUsuario();
        cadastroUsuario.show();
        this.dispose();  
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarUsuario;
    private javax.swing.JButton Historico;
    private javax.swing.JTextField Preferencial;
    private javax.swing.JTextField VagasOcupadas;
    private javax.swing.JTextField VagasRestantes;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
