/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesUsuario;

import bancoDeDados.ConexaoBanco;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import usoGeral.Constantes;

/**
 *
 * @author Guilherme
 */
public class BuscarUsuarios extends javax.swing.JFrame {

    private ConexaoBanco conexaoBanco;
    private Statement statement;
    private ResultSet result;
    private String usuario = "";
    
    public BuscarUsuarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.preencherGrid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        GridUsuarios = new javax.swing.JTable();
        excluir = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        Historico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        GridUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "                                             Nome do Usuário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        GridUsuarios.setColumnSelectionAllowed(true);
        GridUsuarios.getTableHeader().setReorderingAllowed(false);
        GridUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GridUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GridUsuarios);
        GridUsuarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        excluir.setText("Excluir");
        excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excluirMouseClicked(evt);
            }
        });
        excluir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                excluirKeyPressed(evt);
            }
        });

        alterar.setText("Alterar");
        alterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alterarMouseClicked(evt);
            }
        });
        alterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                alterarKeyPressed(evt);
            }
        });

        cadastrar.setText("Cadastrar");
        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarMouseClicked(evt);
            }
        });
        cadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cadastrarKeyPressed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarMouseClicked(evt);
            }
        });
        voltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                voltarKeyPressed(evt);
            }
        });

        Historico.setText("Histórico");
        Historico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoricoMouseClicked(evt);
            }
        });
        Historico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HistoricoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Historico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(voltar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {alterar, excluir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluir)
                    .addComponent(alterar)
                    .addComponent(cadastrar)
                    .addComponent(voltar)
                    .addComponent(Historico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GridUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GridUsuariosMouseClicked
        int linha = GridUsuarios.getSelectedRow();
           
        usuario = GridUsuarios.getValueAt(linha, 0).toString();
    }//GEN-LAST:event_GridUsuariosMouseClicked

    private void voltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarMouseClicked
        this.retornarTela();
    }//GEN-LAST:event_voltarMouseClicked

    private void voltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_voltarKeyPressed
        if (evt.getKeyCode() == 10){
            this.retornarTela();
        }
    }//GEN-LAST:event_voltarKeyPressed

    private void cadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cadastrarKeyPressed
        if (evt.getKeyCode() == 10){
            Constantes.tipoManutencaoUsuario = 0;
            this.chamarCadastroUsuario();
        }
    }//GEN-LAST:event_cadastrarKeyPressed

    private void cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseClicked
        Constantes.tipoManutencaoUsuario = 0;
        this.chamarCadastroUsuario();
    }//GEN-LAST:event_cadastrarMouseClicked

    private void alterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alterarKeyPressed
        if (evt.getKeyCode() == 10){
            if (this.validarUsuario()){
                Constantes.tipoManutencaoUsuario = 1;
                this.chamarCadastroUsuario();
            }
        }
    }//GEN-LAST:event_alterarKeyPressed

    private void alterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alterarMouseClicked
        if (this.validarUsuario()){
            Constantes.tipoManutencaoUsuario = 1;
            this.chamarCadastroUsuario();
        }
    }//GEN-LAST:event_alterarMouseClicked

    private void excluirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_excluirKeyPressed
        if (evt.getKeyCode() == 10){
            this.excluirUsuario();
        }
    }//GEN-LAST:event_excluirKeyPressed

    private void excluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excluirMouseClicked
        this.excluirUsuario();
    }//GEN-LAST:event_excluirMouseClicked

    private void HistoricoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HistoricoKeyPressed
        if (evt.getKeyCode() == 10){
            if (this.validarUsuario()){
                this.buscarHistoricoUsuario(usuario);
            }
        }
    }//GEN-LAST:event_HistoricoKeyPressed

    private void HistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoricoMouseClicked
        if (this.validarUsuario()){
            this.buscarHistoricoUsuario(usuario);
        }
    }//GEN-LAST:event_HistoricoMouseClicked

    private void preencherGrid (){
        try {
            conexaoBanco = new ConexaoBanco();
            statement = conexaoBanco.conexao.createStatement();
            result = statement.executeQuery("SELECT * FROM Usuarios ORDER BY Nome_Usuario");
            
            int i = 0;
            
            while (result.next()){
                if (i < 25){
                    GridUsuarios.setValueAt(result.getString("Nome_Usuario"), i, 0);
                    i++;
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(HistoricoUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } 
        finally{
            try {
                if (statement.isClosed()){
                    statement.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(HistoricoUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void retornarTela(){
        Administracao administracao = new Administracao();
        administracao.show();
        this.dispose();
    }
    
    private void chamarCadastroUsuario (){
        Constantes.usuarioManutencao = usuario;
        CadastroUsuario cadastroUsuario = new CadastroUsuario();
        cadastroUsuario.show();
        this.dispose();  
    }
    
    private boolean validarUsuario(){
        if (this.usuario.equals("")){
            JOptionPane.showMessageDialog(null,"Selecione um usuário.");
            return false;
        }
        else
            return true;
    }
    
    private void excluirUsuario(){
        int confirmacao;
        
        if (this.validarUsuario()){
            confirmacao = JOptionPane.showConfirmDialog(null, "Você confirma a exclusão do usuário " + usuario + "?", "Exclusão", 1);
            if (confirmacao == 0){
                try {
                    conexaoBanco = new ConexaoBanco();
                    statement = conexaoBanco.conexao.createStatement();

                    int deletar = statement.executeUpdate("delete from usuarios where Nome_Usuario = '" + this.usuario + "'");
                    if (deletar > 0){
                        JOptionPane.showMessageDialog(null,"Usuario Removido com Sucesso!");
                        this.retornarTela();
                    } 
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(HistoricoUsuario.class.getName()).log(Level.SEVERE, null, ex);
                } 
                finally{
                    try {
                        if (statement.isClosed()){
                            statement.close();
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(HistoricoUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } 
            }
        }
    }
    
     /**
     * Buscar histórico de usuário e gerar pdf.
     * @return void
     */
    private void buscarHistoricoUsuario(String nomeUsuario){
        Document documento = null;
        OutputStream arquivo = null;
        String nomeArquivo = "";
		
        try {
            //cria o documento tamanho A4, margens de 2,54cm
            documento = new Document(PageSize.A4, 72, 72, 72, 72);
			
            //cria a stream de saída
            nomeArquivo = "historico" + nomeUsuario + ".pdf";
            arquivo = new FileOutputStream(nomeArquivo);
			
            //associa a stream de saída ao 
            PdfWriter.getInstance(documento, arquivo);
			
            //abre o documento
            documento.open();

            //adiciona o texto ao PDF
            Paragraph p = new Paragraph("Usuario: " + nomeUsuario);
            documento.add(p);
            
            Image img = Image.getInstance("ufbalogo.png");
            img.setAlignment(Element.ALIGN_CENTER);
            documento.add(img);
            p.setSpacingAfter(150);
            p = new Paragraph("Estacionamento - Universidade Federal da Bahia");
            p.setAlignment(Element.ALIGN_CENTER);
            documento.add(p);
            p = new Paragraph("\n");
            documento.add(p);
            p = new Paragraph("\n");
            documento.add(p);
          
            conexaoBanco = new ConexaoBanco();
            statement = conexaoBanco.conexao.createStatement();
            result = statement.executeQuery("SELECT * FROM Historico WHERE nomeUsuario_historico = '" + nomeUsuario + "'");
            
            PdfPTable table = new PdfPTable(4);
            PdfPCell header = new PdfPCell(new Paragraph("Histórico de Vaga por usuário"));
            header.setColspan(4);
            table.addCell(header);
            
            table.addCell("             Vaga");
            table.addCell("    Data de Entrada");
            table.addCell("  Horário de Entrada");
            table.addCell("  Horário de Saída");
            
            while (result.next()){
                table.addCell(result.getString("CodigoVaga_historico"));
                table.addCell(result.getString("data_historico"));
                table.addCell(result.getString("horario_entrada_historico"));
                table.addCell(result.getString("horario_saida_historico"));
            }
            
            documento.add(table); 
            
        } 
        catch (DocumentException | IOException e){
            JOptionPane.showMessageDialog(null,"Ocoreu um problema na geração do histórico por Usuário. " + e.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Estacionamento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Estacionamento.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally {
            try{
                if (documento != null) {
                    //fechamento do documento
                    documento.close();
                }
                if (arquivo != null) {
                   //fechamento da stream de saída
                   arquivo.close();
                }
                
                if (statement.isClosed()){
                    statement.close();
                }
                
                try {  
                    File arquivoHistorico = new File(nomeArquivo); 
                    Desktop.getDesktop().open(arquivoHistorico);
                } catch(Exception e) {   
                  JOptionPane.showMessageDialog(null, "Problemas ao abrir arquivo. " + e.getMessage());  
                } 
                
            }
            catch (IOException e){
                JOptionPane.showMessageDialog(null,"Erro ao fechar arquivo.");
            } catch (SQLException ex) {
                Logger.getLogger(Estacionamento.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GridUsuarios;
    private javax.swing.JButton Historico;
    private javax.swing.JButton alterar;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton excluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
