/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesUsuario;

import bancoDeDados.ConexaoBanco;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ControleVagas;
import usoGeral.Constantes;

/**
 * @author Smart Parking
 * @version 1.0
 */
public class CadastroUsuario extends javax.swing.JFrame {

    private ConexaoBanco conexaoBanco;
    private Statement statement;
    private ResultSet result;
    
    /**
     * Creates new form CadastroEstudante
     */
    public CadastroUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        if (Constantes.tipoManutencaoUsuario == 1){
            this.preencherTela();
        }
    }
    
    private void limparCampos (){
        Nome.setText(null);
        CPF.setText(null);
        Matricula.setText(null);
        Curso.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Matricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Curso = new javax.swing.JTextField();
        TemDeficiencia = new javax.swing.JCheckBox();
        Confirmar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        Estudante = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        Senha = new javax.swing.JPasswordField();
        CPF = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("Nome Completo");

        jLabel2.setText("Matrícula/Código de Acesso");

        jLabel3.setText("CPF");

        jLabel4.setText("Curso/Cargo");

        TemDeficiencia.setText("Portador de Deficiência");

        Confirmar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Confirmar.setText("Confirmar");
        Confirmar.setToolTipText("Clique para confirmar gravação.");
        Confirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmarMouseClicked(evt);
            }
        });
        Confirmar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ConfirmarKeyPressed(evt);
            }
        });

        Voltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Voltar.setText("Voltar");
        Voltar.setToolTipText("Clique para cancelar a operação.");
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
        });
        Voltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VoltarKeyPressed(evt);
            }
        });

        Estudante.setText("Estudante");

        jLabel5.setText("Senha");

        try {
            CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CPFFocusLost(evt);
            }
        });

        jLabel6.setText("E-mail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Matricula, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                    .addComponent(Nome)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Curso, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Senha))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(81, 81, 81))
                    .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TemDeficiencia)
                                .addGap(18, 18, 18)
                                .addComponent(Estudante)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Confirmar, Voltar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TemDeficiencia)
                    .addComponent(Estudante))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Confirmar, Voltar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmarMouseClicked
        if (this.validaGravacao()){
            this.gravarUsuario();
        }
    }//GEN-LAST:event_ConfirmarMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void VoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VoltarKeyPressed
        if (evt.getKeyCode() == 10){
            this.retornarTela();
        }
    }//GEN-LAST:event_VoltarKeyPressed

    private void ConfirmarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConfirmarKeyPressed
        if (evt.getKeyCode() == 10){
            if (this.validaGravacao()){
                this.gravarUsuario();
            }
        }
    }//GEN-LAST:event_ConfirmarKeyPressed

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        this.retornarTela();
    }//GEN-LAST:event_VoltarMouseClicked

    private void CPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CPFFocusLost
        if (!(this.validarCPF(CPF.getText().trim()))){
            JOptionPane.showMessageDialog(null,"CPF inválido.", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            CPF.setText("");
        }
    }//GEN-LAST:event_CPFFocusLost

    private void retornarTela(){
        BuscarUsuarios buscarUsuarios = new BuscarUsuarios();
        buscarUsuarios.show();
        this.dispose();
    }
    
     /**
     * Validar gravação de um novo usuário.
     * @return boolean
     */
    private boolean validaGravacao(){
        if ("".equals(Nome.getText().trim())){
            JOptionPane.showMessageDialog(null,"Favor preencher o nome do usuário.", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if ("".equals(CPF.getText().trim())){
            JOptionPane.showMessageDialog(null,"Favor preencher o CPF do usuário.", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if ("".equals(Curso.getText().trim())){
            JOptionPane.showMessageDialog(null,"Favor preencher o curso do usuário.", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if ("".equals(Matricula.getText().trim())){
            JOptionPane.showMessageDialog(null,"Favor preencher o código de acesso do usuário.", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (Constantes.tipoManutencaoUsuario != 1){
            if ("".equals(Senha.getText().trim())){
                JOptionPane.showMessageDialog(null,"Favor preencher a senha do usuário.", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                return false;
            }
        }
        if ("".equals(Email.getText().trim())){
            JOptionPane.showMessageDialog(null,"Favor preencher o E-mail do usuário.", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        try{
           long teste = Long.parseLong(Matricula.getText());
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Favor digitar uma numeração válida para o código de acesso.", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        String matricula = Matricula.getText().trim();
        if (matricula.length() > 8){
            JOptionPane.showMessageDialog(null,"A matrícula deve possuir no máximo 8 caracteres.", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        
        return true;
    }
    
     /**
     * Grava novo usuário no banco de dados.
     * @return void
     */
    private void gravarUsuario(){
        String update, insert;
        
        try {
            conexaoBanco = new ConexaoBanco();
            statement = conexaoBanco.conexao.createStatement();
            result = statement.executeQuery("select * from usuarios where CodigoAcesso_Usuario = " + Integer.parseInt(Matricula.getText()));

            if (result.next()){
                update = "UPDATE usuarios SET ";
                update = update + "Nome_Usuario = '" + Nome.getText() + "', ";
                update = update + "CPF_Usuario = '" + CPF.getText() + "', ";
                if (TemDeficiencia.isSelected()){
                    update = update + "Deficiente_Usuario = 'S', ";
                }
                else{
                    update = update + "Deficiente_Usuario = 'N', ";
                }
                if (Estudante.isSelected()){
                    update = update + "Tipo_Usuario = 'E', ";
                }
                else{
                    update = update + "Tipo_Usuario = 'F', ";
                }
                update = update + "Cargo_Usuario = '" + Curso.getText() + "', ";
                
                if (Constantes.tipoManutencaoUsuario != 1){
                    update = update + "Senha_Usuario = '" + Senha.getText() + "' ";
                }
                
                update = update + "Email_Usuario = '" + Email.getText() + "' ";
                update = update + "WHERE CodigoAcesso_Usuario = " + Matricula.getText();
                int updateStatement = statement.executeUpdate(update);
                if (updateStatement > 0){
                    JOptionPane.showMessageDialog(null,"Usuario Alterado com Sucesso!");
                    this.retornarTela();
                }
            }
            else{
                insert = "INSERT INTO estacionamento.usuarios(Nome_Usuario, CPF_Usuario, CodigoAcesso_Usuario,";
                insert = insert + " Deficiente_Usuario, Tipo_Usuario, Cargo_Usuario, Senha_Usuario, Email_Usuario, CodigoVaga_Usuario) VALUES (";
                insert = insert + "'" + Nome.getText() + "', ";
                insert = insert + "'" + CPF.getText() + "', ";
                insert = insert + Matricula.getText() + ", ";
                if (TemDeficiencia.isSelected()){
                    insert = insert + "'S', ";
                }
                else{
                    insert = insert + "'N', ";
                }
                if (Estudante.isSelected()){
                    insert = insert + "'E', ";
                }
                else{
                    insert = insert + "'F', ";
                }
                insert = insert + "'" + Curso.getText() + "', ";
                insert = insert + "'" + Senha.getText() + "', ";
                insert = insert + "'" + Email.getText() + "', ";
                insert = insert + "' ')";
                int updateStatement = statement.executeUpdate(insert);
                if (updateStatement > 0){
                    JOptionPane.showMessageDialog(null,"Usuario Cadastrado com Sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
                    this.retornarTela();
                }  
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ControleVagas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Erro ao inserir/alterar usuario. \n" + ex.getMessage(), "Cadastro", JOptionPane.ERROR_MESSAGE);
        }
        finally{
            try {
                if (!statement.isClosed()){
                    statement.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(ControleVagas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private boolean validarCPF(String CPF) { 

        char dig10, dig11; 
        int sm, i, r, num, peso;
        
        CPF = CPF.replace(".", "");
        CPF = CPF.replace("-", "");

        if (CPF.equals("00000000000") || CPF.equals("11111111111") || 
            CPF.equals("22222222222") || CPF.equals("33333333333") || 
            CPF.equals("44444444444") || CPF.equals("55555555555") || 
            CPF.equals("66666666666") || CPF.equals("77777777777") || 
            CPF.equals("88888888888") || CPF.equals("99999999999") || (CPF.length() != 11)) 
            return(false);  

        try 
        {
            sm = 0; 
            peso = 10; 

            for (i=0; i<9; i++) 
            {
                num = (int)(CPF.charAt(i) - 48); 
                sm = sm + (num * peso); 
                peso = peso - 1; 
            }

            r = 11 - (sm % 11); 
            if ((r == 10) || (r == 11)) 
                dig10 = '0'; 
            else 
                dig10 = (char)(r + 48);

            sm = 0; 
            peso = 11; 

            for(i=0; i<10; i++) 
            { 
                num = (int)(CPF.charAt(i) - 48); 
                sm = sm + (num * peso); 
                peso = peso - 1; 
            }

            r = 11 - (sm % 11); 
            if ((r == 10) || (r == 11)) 
                dig11 = '0'; 
            else 
                dig11 = (char)(r + 48);

            if ((dig10 == CPF.charAt(9)) && (dig11 == CPF.charAt(10))) 
                return(true); 
            else 
                return(false); 
        } 

        catch (InputMismatchException erro) 
        { 
                return(false); 
        } 
    }
    
    private void preencherTela(){
        try {
            conexaoBanco = new ConexaoBanco();
            statement = conexaoBanco.conexao.createStatement();
            result = statement.executeQuery("SELECT * FROM Usuarios where Nome_Usuario = '" + Constantes.usuarioManutencao + "'");
            
            if (result.next()){
                this.Nome.setText(result.getString("Nome_Usuario"));
                this.CPF.setText(result.getString("CPF_Usuario"));
                this.Matricula.setText(result.getString("CodigoAcesso_Usuario"));
                this.Curso.setText(result.getString("Cargo_Usuario"));
                this.Email.setText(result.getString("Email_Usuario"));
                
                if(result.getString("Deficiente_Usuario").equals("N"))
                    this.TemDeficiencia.setSelected(false);
                else
                    this.TemDeficiencia.setSelected(true);
                
                if(result.getString("Tipo_Usuario").equals("E"))
                    this.Estudante.setSelected(false);
                else
                    this.Estudante.setSelected(true);
                
                this.Senha.enable(false);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(HistoricoUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } 
        finally{
            try {
                if (statement.isClosed()){
                    statement.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(HistoricoUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CPF;
    private javax.swing.JButton Confirmar;
    private javax.swing.JTextField Curso;
    private javax.swing.JTextField Email;
    private javax.swing.JCheckBox Estudante;
    private javax.swing.JTextField Matricula;
    private javax.swing.JTextField Nome;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JCheckBox TemDeficiencia;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
