/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesUsuario;

/**
 * @author Smart Parking
 * @version 1.0
 */
public class TipoHistorico extends javax.swing.JFrame {

    /**
     * Creates new form TipoHistorico
     */
    public TipoHistorico() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HistoricoVaga = new javax.swing.JButton();
        HistoricoUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Escolha o Tipo de Histórico");
        setResizable(false);

        HistoricoVaga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HistoricoVaga.setText("Por Vaga");
        HistoricoVaga.setToolTipText("Clique para abrir o histórico por vaga");
        HistoricoVaga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoricoVagaMouseClicked(evt);
            }
        });
        HistoricoVaga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HistoricoVagaKeyPressed(evt);
            }
        });

        HistoricoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HistoricoUsuario.setText("Por Usuário");
        HistoricoUsuario.setToolTipText("Clique para abrir o histórico por usuarios");
        HistoricoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HistoricoUsuarioMouseClicked(evt);
            }
        });
        HistoricoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HistoricoUsuarioKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HistoricoVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistoricoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(HistoricoVaga, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(HistoricoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HistoricoVagaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HistoricoVagaKeyPressed
        if (evt.getKeyCode() == 10){
            this.historicoPorVaga();
        }
    }//GEN-LAST:event_HistoricoVagaKeyPressed

    private void HistoricoVagaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoricoVagaMouseClicked
        this.historicoPorVaga();
    }//GEN-LAST:event_HistoricoVagaMouseClicked

    private void HistoricoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HistoricoUsuarioKeyPressed
        if (evt.getKeyCode() == 10){
            this.historicoPorUsuario();
        }
    }//GEN-LAST:event_HistoricoUsuarioKeyPressed

    private void HistoricoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HistoricoUsuarioMouseClicked
        this.historicoPorUsuario();
    }//GEN-LAST:event_HistoricoUsuarioMouseClicked

    private void historicoPorVaga (){
        Estacionamento estacionamento = new Estacionamento();
        estacionamento.show();
        this.dispose();  
    }
    
    private void historicoPorUsuario (){
        HistoricoUsuario historicoUsuario = new HistoricoUsuario();
        historicoUsuario.show();
        this.dispose();  
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HistoricoUsuario;
    private javax.swing.JButton HistoricoVaga;
    // End of variables declaration//GEN-END:variables
}
